### ISSUE TITLE
Piggyback 

### ISSUE THREAD

**Issue by giannaros900** [FL0WL0W/EFIGenieSTM32F401C#2]
Is there Piggyback decoder available???

**Comment by FL0WL0W** [comment]
Can you give me some detail on how this decoder is supposed to work? What is the source of the timing? Is it just an ignition or injection input that you get the rotation angle? I can put something together. 

This is the repo for the Reluctor decoders. https://github.com/FL0WL0W/ReluctorOperations
This reluctor is probably pretty similar to what you need and could potentially add configuration on whether to trigger on the rising edge, falling edge, or both. https://github.com/FL0WL0W/ReluctorOperations/blob/main/src/Operations/Operation_ReluctorUniversal1x.cpp

**Comment by giannaros900** [comment]
Just for fueling...(in my case 2 cylinder). We can use the oem injector signal

**Comment by FL0WL0W** [comment]
Ok, I just added the ability to select what edges to capture on for the Universal1X Reluctor decoder. Use that and it's probably best to select Falling Edge as most fueling strategies select when to end the pulse rather than when to start the pulse.

https://github.com/FL0WL0W/ReluctorOperations/commit/9e02adf0dc857f1e1dcf6c03411b5fe5b13f34c4

**Comment by giannaros900** [comment]
Yes the falling edge is the best.... Good job!!!
